import './globals.css'
import GoogleAnalytics from "@/components/GoogleAnalytics";
import "../libraries/bootstrap/css/bootstrap.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const font = Onest(
  { subsets: ["latin"],
    weight: '400'
}
  );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body 
      
      suppressHydrationWarning={true}
      className={font.className}>
        <GoogleAnalytics GA_MEASUREMENT_ID={''}/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
